// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmikxfszhisaqjqgsmnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtaWt4ZnN6aGlzYXFqcWdzbW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2NjE5NTQsImV4cCI6MjA5MDIzNzk1NH0.EiySrTE0KzQSJnWfMYDt868r8LRAxSj32qXKXvMUXHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});